### PR TITLE
Include LICENSE in sdist

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by takluyver** [comment]
Hey @hroncok. Thanks, this is fine.

`intreehooks` is largely obsolete now, as PEP 517 gained a standard mechanism (`backend-path`) which can achieve the same result without an external package. I should put that in the README.

**Comment by hroncok** [comment]
Thanks for the info. Definitively, please do.

**Comment by takluyver** [comment]
Done :)

**Comment by hroncok** [comment]
Thank You.

**Pull request merged**
